name: sturner.com
favicon: null
layout_spectrum: 0.33855111873708665
typography_spectrum: 0.06981964339502156
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.7487028441391885
  lightness: 0.8592327462974936
  saturation: 0.9860570246819407
  rhythmicContrast: 0.7803867699112743
purpose: []
